version: "3.7"

services:
  cloudflared:
    container_name: cloudflared
    build: src/cloudflared/
    ports:
      - "5053:5053" #Custom dns port
    volumes:
      - "/docker/cloudflared-hole/cloudflared/:/cloudflared/"
    networks:
      cloudflared-hole_net:
        ipv4_address: 10.0.0.2
    healthcheck:
      test: ["CMD", "nslookup", "-query=A", "-port=5053", "one.one.one.one", "127.0.0.1"]
      interval: 1m
      timeout: 5s
      retries: 3
    restart: unless-stopped

  # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp" #DNS
      - "53:53/udp" #DNS
      #- "67:67/udp" #DHCP
      - "80:80/tcp" #HTTP
      - "443:443/tcp" #HTTPS
    environment:
      TZ: "Europe/Budapest"
      WEBPASSWORD: ""
      DNS1: 10.0.0.2#5053 #DNS provided by the "cloudflared" service
      DNS2: "no"
      IPV6: "false"
      #DNSMASQ_USER: "pihole"
    volumes:
      - '/docker/cloudflared-hole/pihole/etc-pihole/:/etc/pihole/'
      - '/docker/cloudflared-hole/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 1.0.0.1
    networks:
      cloudflared-hole_net:
        ipv4_address: 10.0.0.3
    restart: unless-stopped

networks:
  cloudflared-hole_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/29
